messagebroker:
  broker_addr: localhost:9092
  group_id: consumer-email
  topic: mailsender
  key: message
smtp:
  addr: localhost:1025
  no_reply_email_addr: "no@reply.ru"
messagehandler:
  rate_microseconds: 10000000