version: "3.9"
services:
  maildev:
    image: maildev/maildev
    ports: 
      - "1025:1025"
      - "1080:1080"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data-vol:/var/lib/zookeeper/data
      - zookeeper-log-vol:/var/lib/zookeeper/log
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "mailsender:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-vol:/var/lib/kafka/data
volumes:
  kafka-vol:
  zookeeper-data-vol:
  zookeeper-log-vol: